export   const TASK_POST_SUCCESS="TASK_POST_SUCCESS"
export   const TASK_GET_SUCCESS="TASK_GET_SUCCESS"
export   const TASK_DELETE_SUCCESS="TASK_DELETE_SUCCESS"
export   const TASK_EDIT_SUCCESS="TASK_EDIT_SUCCESS"